language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25

jdk:
  - oraclejdk8
before_install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
script: ./gradlew build # domyślnie: ./gradlew build connectedCheck
